# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui_code.resource_rc import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 640)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.originalImg = QtWidgets.QLabel(self.centralwidget)
        self.originalImg.setEnabled(True)
        self.originalImg.setGeometry(QtCore.QRect(10, 10, 451, 441))
        self.originalImg.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.originalImg.setFrameShadow(QtWidgets.QFrame.Plain)
        self.originalImg.setAlignment(QtCore.Qt.AlignCenter)
        self.originalImg.setObjectName("originalImg")
        self.newImg = QtWidgets.QLabel(self.centralwidget)
        self.newImg.setGeometry(QtCore.QRect(500, 10, 451, 441))
        self.newImg.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.newImg.setAlignment(QtCore.Qt.AlignCenter)
        self.newImg.setObjectName("newImg")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 172, 20, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.style1 = QtWidgets.QPushButton(self.centralwidget)
        self.style1.path = "asset/style1.jpg"
        self.style1.setGeometry(QtCore.QRect(50, 480, 111, 101))
        self.style1.setAutoFillBackground(False)
        self.style1.setStyleSheet("QPushButton{\n"
"border-image: url(:/styles/asset/style1.jpg);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px;\n"
"}\n"
"")
        self.style1.setText("")
        self.style1.setObjectName("style1")
        self.style2 = QtWidgets.QPushButton(self.centralwidget)
        self.style2.path = "asset/style2.jpg"
        self.style2.setGeometry(QtCore.QRect(190, 480, 111, 101))
        self.style2.setStyleSheet("QPushButton{\n"
"border-image: url(:/styles/asset/style2.jpg);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px;\n"
"}")
        self.style2.setText("")
        self.style2.setObjectName("style2")
        self.style3 = QtWidgets.QPushButton(self.centralwidget)
        self.style3.path = "asset/style3.jpg"
        self.style3.setGeometry(QtCore.QRect(330, 480, 111, 101))
        self.style3.setStyleSheet("QPushButton{\n"
"border-image: url(:/styles/asset/style3.jpg);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px;\n"
"}")
        self.style3.setText("")
        self.style3.setObjectName("style3")
        self.style4 = QtWidgets.QPushButton(self.centralwidget)
        self.style4.path = "asset/style4.jpg"
        self.style4.setGeometry(QtCore.QRect(470, 480, 111, 101))
        self.style4.setStyleSheet("QPushButton{\n"
"border-image: url(:/styles/asset/style4.jpg);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 10px;\n"
"}")
        self.style4.setText("")
        self.style4.setObjectName("style4")
        self.styleImg = QtWidgets.QLabel(self.centralwidget)
        self.styleImg.setGeometry(QtCore.QRect(750, 470, 151, 141))
        self.styleImg.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.styleImg.setText("")
        self.styleImg.setAlignment(QtCore.Qt.AlignCenter)
        self.styleImg.setObjectName("styleImg")
        self.otherstyle = QtWidgets.QPushButton(self.centralwidget)
        self.otherstyle.setGeometry(QtCore.QRect(600, 500, 131, 31))
        self.otherstyle.setObjectName("otherstyle")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 470, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 540, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(500, 450, 451, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.hide()
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 595, 741, 21))
        self.label.setText("")
        self.label.setStyleSheet("color: rgb(255, 0, 0)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(500, 448, 451, 20))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSaveAs)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Style Transfer using CNN"))
        self.originalImg.setText(_translate("MainWindow", "Original Image here"))
        self.newImg.setText(_translate("MainWindow", "New image here"))
        self.label_3.setText(_translate("MainWindow", ">"))
        self.otherstyle.setText(_translate("MainWindow", "Choose your own style"))
        self.label_5.setText(_translate("MainWindow", "Style Image"))
        self.pushButton.setText(_translate("MainWindow", "Transfer"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())